services:
  broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # Send and receive messages
      - "15672:15672" # GUI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  
volumes:
  rabbitmq_data: